apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-world-api-build
  labels:
    app: hello-world-api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hello-world-api:latest
  source:
    type: Git
    git:
      uri: https://github.com/gheorghitamutu/hello-world-api.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
  - type: Generic
    generic:
      secret: generic-webhook-secret
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hello-world-api
  labels:
    app: hello-world-api
spec:
  lookupPolicy:
    local: false
